version: '3'

services:
  lb:
    image: haproxy
    ports:
      - "8080:8080"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
    depends_on:
      - comapp1
      - comapp2
      - comapp3
      - comapp4

  chatapp1:
    image: comapp
    hostname: 'comapp1'
    environment:
      - SERVER_NAME=comAPP-1
      - REDIS_HOST=rds
      - MONGO=mongodb://mongo:27017/DistributedCommunication
    depends_on: 
      - rds
      - mongo

  chatapp2:
    image: comapp
    hostname: 'comapp2'
    environment:
      - SERVER_NAME=comAPP-2
      - REDIS_HOST=rds
      - MONGO=mongodb://mongo:27017/DistributedCommunication
    depends_on: 
      - rds
      - mongo

  chatapp3:
    image: comapp
    hostname: 'comapp3'
    environment:
      - SERVER_NAME=comAPP-3
      - REDIS_HOST=rds
      - MONGO=mongodb://mongo:27017/DistributedCommunication
    depends_on: 
      - rds
      - mongo

  chatapp4:
    image: comapp
    hostname: 'comapp4'
    environment:
      - SERVER_NAME=comAPP-4
      - REDIS_HOST=rds
      - MONGO=mongodb://mongo:27017/DistributedCommunication
    depends_on: 
      - rds
      - mongo
  
  rds:
    image: redis

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    


